### ISSUE TITLE
support new time conductor API

### ISSUE THREAD

**Issue by larkin** [nasa/openmct-demo#2]
need to update code to utilize new time conductor API in https://github.com/nasa/openmct/pull/1553

**Comment by larkin** [comment]
https://github.com/nasa/openmct-demo/blob/master/scripts/demo-time-conductor.js should be updated to use the time api to change modes instead of using `$location`

**Comment by bryan-lunt** [comment]
This, or a related issue, seems to prevent these demos from running at all for me.

`Error: Invalid Time Conductor Configuration: 
You must specify one or more 'menuOptions'.
https://github.com/nasa/openmct/blob/master/API.md#the-time-conductor`

**Comment by larkin** [comment]
Fixed by 1f9f39c63a6a57bbdf6110162b7b07b0956f99d8.
